---
- hosts: localhost
  tasks:
    - name: install tmux
      ansible.builtin.package:
        name: tmux
        state: present
      become: true

    - name: Install docker with ansible
      include_role:
        name: geerlingguy.docker
        apply:
          become: true
      vars:
        docker_users:
          - "{{ lookup('ansible.builtin.env', 'USER') }}"
